using BepInEx.Configuration;

namespace ESP {
  public partial class Settings {
    public static ConfigEntry<float> configCreatureFireLineWidth;
    public static float CreatureFireLineWidth => configCreatureFireLineWidth.Value;
    public static ConfigEntry<float> configCreatureRayWidth;
    public static float CreatureRayWidth => configCreatureRayWidth.Value;
    public static ConfigEntry<float> configBreedingLineWidth;
    public static float BreedingLineWidth => configBreedingLineWidth.Value;
    public static ConfigEntry<float> configCoverRayWidth;
    public static float CoverRayWidth => configCoverRayWidth.Value;
    public static ConfigEntry<float> configPlayerCoverRayWidth;
    public static float PlayerCoverRayWidth => configPlayerCoverRayWidth.Value;
    public static ConfigEntry<float> configSmokeLineWidth;
    public static float SmokeLineWidth => configSmokeLineWidth.Value;
    public static ConfigEntry<float> configSenseLineWidth;
    public static float SenseLineWidth => configSenseLineWidth.Value;
    public static ConfigEntry<float> configNoiseLineWidth;
    public static float NoiseLineWidth => configNoiseLineWidth.Value;
    public static ConfigEntry<float> configSpawnSystemRayWidth;
    public static float SpawnSystemRayWidth => configSpawnSystemRayWidth.Value;
    public static ConfigEntry<float> configRandEventSystemRayWidth;
    public static float RandEventSystemRayWidth => configRandEventSystemRayWidth.Value;
    public static ConfigEntry<float> configSpawnAreasLineWidth;
    public static float SpawnAreasLineWidth => configSpawnAreasLineWidth.Value;
    public static ConfigEntry<float> configCreatureSpawnerRayWidth;
    public static float CreatureSpawnersRayWidth => configCreatureSpawnerRayWidth.Value;
    public static ConfigEntry<float> configBiomeCornerRayWidth;
    public static float BiomeCornerRayWidth => configBiomeCornerRayWidth.Value;
    public static ConfigEntry<float> configPickableRayWidth;
    public static float PickableRayWidth => configPickableRayWidth.Value;
    public static ConfigEntry<float> configEffectAreaLineWidth;
    public static float EffectAreaLineWidth => configEffectAreaLineWidth.Value;
    public static ConfigEntry<float> configCustomContainerEffectAreaRadius;
    public static float CustomContainerEffectAreaRadius => configCustomContainerEffectAreaRadius.Value;
    public static ConfigEntry<float> configCustomCraftingEffectAreaRadius;
    public static float CustomCraftingEffectAreaRadius => configCustomCraftingEffectAreaRadius.Value;
    public static ConfigEntry<float> configRulerRadius;
    public static float RulerRadius => configRulerRadius.Value;
    public static ConfigEntry<float> configChestRayWidth;
    public static float ChestRayWidth => configChestRayWidth.Value;
    public static ConfigEntry<float> configOreRayWidth;
    public static float OreRayWidth => configOreRayWidth.Value;
    public static ConfigEntry<float> configTreeRayWidth;
    public static float TreeRayWidth => configTreeRayWidth.Value;
    public static ConfigEntry<float> configDestructibleRayWidth;
    public static float DestructibleRayWidth => configDestructibleRayWidth.Value;
    public static ConfigEntry<float> configLocationRayWidth;
    public static float LocationRayWidth => configLocationRayWidth.Value;
    public static ConfigEntry<bool> configShowSupport;
    public static bool ShowSupport => configShowSupport.Value;
    public static void InitVisuals(ConfigFile config) {
      var section = "4. Visuals";
      configShowZones = config.Bind(section, "Show zones", false, "Show visualization for zones (toggle with Y button in the game)");
      configShowCreatures = config.Bind(section, "Show creatures", false, "Show visualization for creatures (toggle with U button in the game)");
      configShowOthers = config.Bind(section, "Show visualization", false, "Show visualization for everything else (toggle with I button in the game)");
      configCreatureFireLineWidth = config.Bind(section, "Creature fire alert range", 0.1f, "Vsualize radius of fire fearing");
      configSenseLineWidth = config.Bind(section, "Creature senses", 0.1f, "Line width of sight and hear ranges (0 to disable)");
      configBreedingLineWidth = config.Bind(section, "Breeding limits", 0.1f, "Visualize breeding parther check and total limit ranges");
      configCoverRayWidth = config.Bind(section, "Cover rays", 0.1f, "Visualize cover check rays");
      configPlayerCoverRayWidth = config.Bind(section, "Player cover rays", 0.0f, "Visualize cover check rays for players");
      configSmokeLineWidth = config.Bind(section, "Smoke", 0.1f, "Visualize smoke particles");
      configCreatureRayWidth = config.Bind(section, "Creature rays", 0.25f, "Line width for tracked creature locations (0 to disable)");
      configCreatureSpawnerRayWidth = config.Bind(section, "Spawn points", 0.1f, "Line width of fixed creature spawn points (0 to disable)");
      configSpawnAreasLineWidth = config.Bind(section, "Creature spawners", 0.1f, "Line width of physical creature spawner ranges (0 to disable)");
      configSpawnSystemRayWidth = config.Bind(section, "Spawn zones", 0.5f, "Line width of spawn zone system (0 to disable)");
      configBiomeCornerRayWidth = config.Bind(section, "Zone corner rays", 0.25f, "Line width of zone corners (0 to disable)");
      configRandEventSystemRayWidth = config.Bind(section, "Random event system", 0.5f, "Line width of random event system (0 to disable)");
      configPickableRayWidth = config.Bind(section, "Pickable rays", 0.1f, "Line width of pickable locations (0 to disable)");
      configRulerRadius = config.Bind(section, "Ruler point radius", 0.5f, "Ruler point radius (0 to disable)");
      configChestRayWidth = config.Bind(section, "Chest rays", 0.1f, "Line width of hidden chest locations (0 to disable)");
      configOreRayWidth = config.Bind(section, "Ore rays", 0.1f, "Line width of ore locations (0 to disable)");
      configTreeRayWidth = config.Bind(section, "Tree rays", 0f, "Line width of tree locations (0 to disable)");
      configDestructibleRayWidth = config.Bind(section, "Destructible rays", 0f, "Line width of destructible locations (0 to disable)");
      configLocationRayWidth = config.Bind(section, "Location rays", 0.5f, "Line width of pre-generated structure locations (0 to disable)");
      configShowSupport = config.Bind(section, "Support", true, "Always show support color for structures");
      configEffectAreaLineWidth = config.Bind(section, "Area effects", 0.1f, "Line width of area effect ranges (0 to disable)");
      configCustomContainerEffectAreaRadius = config.Bind(section, "Custom radius for containers", 0.0f, "Custom effect area sphere for containers (0 to disable)");
      configCustomCraftingEffectAreaRadius = config.Bind(section, "Custom radius for crafting stations", 0.0f, "Custom effect area sphere for crafting stations (0 to disable)");
      configNoiseLineWidth = config.Bind(section, "Noise", 0.0f, "Line width of noise range (0 to disable)");
    }
  }
}
