using System;
using BepInEx.Configuration;
using Service;
using Visualization;
namespace ESP;

public partial class Settings
{
#nullable disable
  public static ConfigEntry<bool> configShowCreatureColliders;
  public static ConfigEntry<bool> configShowStructureColliders;
  public static ConfigEntry<bool> configShowDestructibleColliders;
  public static ConfigEntry<bool> configShowAttackRange;
  public static ConfigEntry<bool> configShowCreatureFireRange;
  public static ConfigEntry<bool> configShowTrackedObjects;
  public static ConfigEntry<bool> configShowCreatureBreedingTotalRange;
  public static ConfigEntry<bool> configShowCreatureBreedingPartnerRange;
  public static ConfigEntry<bool> configShowCreatureFoodSearchRange;
  public static ConfigEntry<bool> configShowCreatureEatingRange;
  public static ConfigEntry<bool> configShowStructureCover;
  public static ConfigEntry<bool> configShowPlayerCover;
  public static ConfigEntry<bool> configShowSmoke;
  public static ConfigEntry<bool> configShowCreatureAlertRange;
  public static ConfigEntry<bool> configShowCreatureNoise;
  public static ConfigEntry<bool> configShowCreatureHearRange;
  public static ConfigEntry<bool> configShowCreatureViewRange;
  public static ConfigEntry<bool> configShowSpawnZones;
  public static ConfigEntry<bool> configShowRandomEventSystem;
  public static ConfigEntry<bool> configShowSpawnerRays;
  public static ConfigEntry<bool> configShowSpawnerTriggerRanges;
  public static ConfigEntry<bool> configShowSpawnerLimitRanges;
  public static ConfigEntry<bool> configShowSpawnerSpawnRanges;
  public static ConfigEntry<bool> configShowAltarRays;
  public static ConfigEntry<bool> configShowAltarItemStandRange;
  public static ConfigEntry<bool> configShowAltarSpawnRadius;
  public static ConfigEntry<bool> configShowSpawnPointsOneTime;
  public static ConfigEntry<bool> configShowSpawnPointsRespawning;
  public static ConfigEntry<bool> configShowZoneCorners;
  public static ConfigEntry<bool> configShowPickablesOneTime;
  public static ConfigEntry<bool> configShowPickablesRespawning;
  public static ConfigEntry<bool> configShowEffectAreasPrivateArea;
  public static ConfigEntry<bool> configShowEffectAreasComfort;
  public static ConfigEntry<bool> configShowEffectAreasBurning;
  public static ConfigEntry<bool> configShowEffectAreasHeat;
  public static ConfigEntry<bool> configShowEffectAreasFire;
  public static ConfigEntry<bool> configShowEffectAreasNoMonsters;
  public static ConfigEntry<bool> configShowEffectAreasTeleport;
  public static ConfigEntry<bool> configShowSpawnSuppression;
  public static ConfigEntry<bool> configShowEffectAreasWarmCozy;
  public static ConfigEntry<bool> configShowEffectAreasOther;
  public static ConfigEntry<bool> configShowEffectAreasCustomContainer;
  public static ConfigEntry<bool> configShowEffectAreasCustomCrafting;
  public static ConfigEntry<bool> configShowChests;
  public static ConfigEntry<bool> configShowOres;
  public static ConfigEntry<bool> configShowTrees;
  public static ConfigEntry<bool> configShowDestructibles;
  public static ConfigEntry<bool> configShowTrophySpeaks;
  public static ConfigEntry<bool> configShowLocations;
  public static ConfigEntry<bool> configShowEventZones;
  public static ConfigEntry<bool> configShowStructureSupport;
  private static ConfigEntry<bool> GetTagEntry(string name)
  {
    name = name.ToLower();
    if (name == Tag.CreatureCollider.ToLower()) return configShowCreatureColliders;
    if (name == Tag.StructureCollider.ToLower()) return configShowStructureColliders;
    if (name == Tag.DestructibleCollider.ToLower()) return configShowDestructibleColliders;
    if (name == Tag.StructureCover.ToLower()) return configShowStructureCover;
    if (name == Tag.StructureCoverBlocked.ToLower()) return configShowStructureCover;
    if (name == Tag.StructureSupport.ToLower()) return configShowStructureSupport;
    if (name == Tag.CreatureNoise.ToLower()) return configShowCreatureNoise;
    if (name == Tag.CreatureHearRange.ToLower()) return configShowCreatureHearRange;
    if (name == Tag.CreatureViewRange.ToLower()) return configShowCreatureViewRange;
    if (name == Tag.CreatureAlertRange.ToLower()) return configShowCreatureAlertRange;
    if (name == Tag.Attack.ToLower()) return configShowAttackRange;
    if (name == Tag.CreatureFireRange.ToLower()) return configShowCreatureFireRange;
    if (name == Tag.CreatureBreedingTotalRange.ToLower()) return configShowCreatureBreedingTotalRange;
    if (name == Tag.CreatureBreedingPartnerRange.ToLower()) return configShowCreatureBreedingPartnerRange;
    if (name == Tag.CreatureFoodSearchRange.ToLower()) return configShowCreatureFoodSearchRange;
    if (name == Tag.CreatureEatingRange.ToLower()) return configShowCreatureEatingRange;
    if (name == Tag.TrackedObject.ToLower()) return configShowTrackedObjects;
    if (name == Tag.PickableOneTime.ToLower()) return configShowPickablesOneTime;
    if (name == Tag.PickableRespawning.ToLower()) return configShowPickablesRespawning;
    if (name == Tag.Location.ToLower()) return configShowLocations;
    if (name == Tag.EventZone.ToLower()) return configShowEventZones;
    if (name == Tag.Chest.ToLower()) return configShowChests;
    if (name == Tag.Tree.ToLower()) return configShowTrees;
    if (name == Tag.Ore.ToLower()) return configShowOres;
    if (name == Tag.Destructible.ToLower()) return configShowDestructibles;
    if (name == Tag.TrophySpeak.ToLower()) return configShowTrophySpeaks;
    if (name == Tag.SpawnPointOneTime.ToLower()) return configShowSpawnPointsOneTime;
    if (name == Tag.SpawnPointRespawning.ToLower()) return configShowSpawnPointsRespawning;
    if (name == Tag.SpawnerRay.ToLower()) return configShowSpawnerRays;
    if (name == Tag.SpawnerTriggerRange.ToLower()) return configShowSpawnerTriggerRanges;
    if (name == Tag.SpawnerLimitRange.ToLower()) return configShowSpawnerLimitRanges;
    if (name == Tag.SpawnerSpawnRange.ToLower()) return configShowSpawnerSpawnRanges;
    if (name == Tag.AltarRay.ToLower()) return configShowAltarRays;
    if (name == Tag.AltarItemStandRange.ToLower()) return configShowAltarItemStandRange;
    if (name == Tag.AltarSpawnRadius.ToLower()) return configShowAltarSpawnRadius;
    if (name == Tag.ZoneCorner.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerAshlands.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerBlackForest.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerDeepNorth.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerMeadows.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerMistlands.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerMountain.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerOcean.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerPlains.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerSwamp.ToLower()) return configShowZoneCorners;
    if (name == Tag.ZoneCornerUnknown.ToLower()) return configShowZoneCorners;
    if (name == Tag.SpawnZone.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZoneAshlands.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZoneBlackForest.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZoneDeepNorth.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZoneMeadows.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZoneMistlands.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZoneMountain.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZoneOcean.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZonePlains.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZoneSwamp.ToLower()) return configShowSpawnZones;
    if (name == Tag.SpawnZoneUnknown.ToLower()) return configShowSpawnZones;
    if (name == Tag.RandomEventSystem.ToLower()) return configShowRandomEventSystem;
    if (name == Tag.EffectAreaBurning.ToLower()) return configShowEffectAreasBurning;
    if (name == Tag.EffectAreaComfort.ToLower()) return configShowEffectAreasComfort;
    if (name == Tag.EffectAreaCustomContainer.ToLower()) return configShowEffectAreasCustomContainer;
    if (name == Tag.EffectAreaCustomCrafting.ToLower()) return configShowEffectAreasCustomCrafting;
    if (name == Tag.EffectAreaFire.ToLower()) return configShowEffectAreasFire;
    if (name == Tag.EffectAreaHeat.ToLower()) return configShowEffectAreasHeat;
    if (name == Tag.EffectAreaNoMonsters.ToLower()) return configShowEffectAreasNoMonsters;
    if (name == Tag.EffectAreaOther.ToLower()) return configShowEffectAreasOther;
    if (name == Tag.EffectAreaPlayerBase.ToLower()) return configShowSpawnSuppression;
    if (name == Tag.EffectAreaWarmCozy.ToLower()) return configShowEffectAreasWarmCozy;
    if (name == Tag.EffectAreaPrivateArea.ToLower()) return configShowEffectAreasPrivateArea;
    if (name == Tag.EffectAreaTeleport.ToLower()) return configShowEffectAreasTeleport;
    if (name == Tag.Smoke.ToLower()) return configShowSmoke;
    if (name == Tag.PlayerCover.ToLower()) return configShowPlayerCover;
    if (name == Tag.PlayerCoverBlocked.ToLower()) return configShowPlayerCover;
    throw new NotImplementedException(name);
  }
  public static bool IsDisabled(string name)
  {
    return !PermissionManager.IsFeatureEnabledByHash(Visibility.GetTagHash(name), GetTagEntry(name).Value);
  }
  public static bool IsHidden(string name)
  {
    return !PermissionManager.IsFeatureEnabledByHash(Visibility.GetTagHash(name), GetTagEntry(name).Value);
  }
  private static ConfigDescription CreateDescription() => new("");
  private static void OnChanged(ConfigEntry<bool> entry, string tag, params Action[] rebuilds)
  {
    foreach (var rebuild in rebuilds)
    {
      if (rebuild != null) Visibility.RegisterRebuilder(tag, rebuild);
    }
    entry.SettingChanged += (s, e) => Visibility.SetTag(tag, entry.Value);
    Visibility.SetTag(tag, entry.Value);
  }
  private static void InitVisuals(ConfigFile config)
  {
    var section = "3. Visuals";
    configShowCreatureColliders = config.Bind(section, "Creature colliders", false, CreateDescription());
    OnChanged(configShowCreatureColliders, Tag.CreatureCollider, Character_Colliders.RebuildLoaded);
    configShowStructureColliders = config.Bind(section, "Structure colliders", false, CreateDescription());
    OnChanged(configShowStructureColliders, Tag.StructureCollider, WearNTear_Colliders.RebuildLoaded);
    configShowDestructibleColliders = config.Bind(section, "Destructible colliders", false, CreateDescription());
    OnChanged(configShowDestructibleColliders, Tag.DestructibleCollider, Destructible_Colliders.RebuildLoaded);
    configShowAttackRange = config.Bind(section, "Attack range", false, CreateDescription());
    OnChanged(configShowAttackRange, Tag.Attack);
    configShowStructureCover = config.Bind(section, "Structure cover", false, CreateDescription());
    OnChanged(configShowStructureCover, Tag.StructureCover, Piece_Visual.RebuildLoaded);
    OnChanged(configShowStructureCover, Tag.StructureCoverBlocked, Piece_Visual.RebuildLoaded);
    configShowStructureCover.SettingChanged += (s, e) => SupportUtils.UpdateVisibility();
    configShowStructureSupport = config.Bind(section, "Structure support", false, CreateDescription());
    OnChanged(configShowStructureSupport, Tag.StructureSupport, SupportUtils.UpdateVisibility);
    configShowCreatureNoise = config.Bind(section, "Creature noise", false, CreateDescription());
    OnChanged(configShowCreatureNoise, Tag.CreatureNoise, Character_Awake.RebuildLoaded);
    configShowCreatureHearRange = config.Bind(section, "Creature hear range", false, CreateDescription());
    OnChanged(configShowCreatureHearRange, Tag.CreatureHearRange, BaseAI_Awake.RebuildLoaded);
    configShowCreatureViewRange = config.Bind(section, "Creature view range", false, CreateDescription());
    OnChanged(configShowCreatureViewRange, Tag.CreatureViewRange, BaseAI_Awake.RebuildLoaded);
    configShowCreatureAlertRange = config.Bind(section, "Creature alert range", false, CreateDescription());
    OnChanged(configShowCreatureAlertRange, Tag.CreatureAlertRange, BaseAI_Awake.RebuildLoaded);
    configShowCreatureFireRange = config.Bind(section, "Creature fire range", false, CreateDescription());
    OnChanged(configShowCreatureFireRange, Tag.CreatureFireRange, BaseAI_Awake.RebuildLoaded);
    configShowCreatureBreedingTotalRange = config.Bind(section, "Creature breeding total range", false, CreateDescription());
    OnChanged(configShowCreatureBreedingTotalRange, Tag.CreatureBreedingTotalRange, BaseAI_Awake.RebuildLoaded);
    configShowCreatureBreedingPartnerRange = config.Bind(section, "Creature breeding partner range", false, CreateDescription());
    OnChanged(configShowCreatureBreedingPartnerRange, Tag.CreatureBreedingPartnerRange, BaseAI_Awake.RebuildLoaded);
    configShowCreatureEatingRange = config.Bind(section, "Creature eating range", false, CreateDescription());
    OnChanged(configShowCreatureEatingRange, Tag.CreatureEatingRange, BaseAI_Awake.RebuildLoaded);
    configShowCreatureFoodSearchRange = config.Bind(section, "Creature food search range", false, CreateDescription());
    OnChanged(configShowCreatureFoodSearchRange, Tag.CreatureFoodSearchRange, BaseAI_Awake.RebuildLoaded);
    configShowTrackedObjects = config.Bind(section, "Tracked object rays", false, CreateDescription());
    OnChanged(configShowTrackedObjects, Tag.TrackedObject, ZNetView_Ray.RebuildLoaded);
    configShowPickablesOneTime = config.Bind(section, "Pickable rays (one time)", false, CreateDescription());
    OnChanged(configShowPickablesOneTime, Tag.PickableOneTime, Pickable_Ray.RebuildLoaded);
    configShowPickablesRespawning = config.Bind(section, "Pickable rays (respawning)", false, CreateDescription());
    OnChanged(configShowPickablesRespawning, Tag.PickableRespawning, Pickable_Ray.RebuildLoaded);
    configShowLocations = config.Bind(section, "Location rays", false, CreateDescription());
    OnChanged(configShowLocations, Tag.Location, Location_Ray.RebuildLoaded);
    configShowEventZones = config.Bind(section, "Event zone rays", false, CreateDescription());
    OnChanged(configShowEventZones, Tag.EventZone, EventZone_Ray.RebuildLoaded);
    configShowChests = config.Bind(section, "Chest rays", false, CreateDescription());
    OnChanged(configShowChests, Tag.Chest, Container_Ray.RebuildLoaded);
    configShowTrees = config.Bind(section, "Tree rays", false, CreateDescription());
    OnChanged(configShowTrees, Tag.Tree, TreeLog_Ray.RebuildLoaded, TreeBase_Ray.RebuildLoaded, MineRock_Ray.RebuildLoaded, MineRock5_Ray.RebuildLoaded, Destructible_Ray.RebuildLoaded);
    configShowOres = config.Bind(section, "Ore rays", false, CreateDescription());
    OnChanged(configShowOres, Tag.Ore, MineRock_Ray.RebuildLoaded, MineRock5_Ray.RebuildLoaded, Destructible_Ray.RebuildLoaded);
    configShowTrophySpeaks = config.Bind(section, "Trophy speak spheres", false, CreateDescription());
    OnChanged(configShowTrophySpeaks, Tag.TrophySpeak, RandomSpeak_Sphere.RebuildLoaded);
    configShowDestructibles = config.Bind(section, "Destructible rays", false, CreateDescription());
    OnChanged(configShowDestructibles, Tag.Destructible, MineRock_Ray.RebuildLoaded, MineRock5_Ray.RebuildLoaded, Destructible_Ray.RebuildLoaded);
    configShowSpawnPointsOneTime = config.Bind(section, "Spawn points (one time)", false, CreateDescription());
    OnChanged(configShowSpawnPointsOneTime, Tag.SpawnPointOneTime, CreatureSpawner_Ray.RebuildLoaded);
    configShowSpawnPointsRespawning = config.Bind(section, "Spawn points (respawning)", false, CreateDescription());
    OnChanged(configShowSpawnPointsRespawning, Tag.SpawnPointRespawning, CreatureSpawner_Ray.RebuildLoaded);
    configShowSpawnerRays = config.Bind(section, "Creature spawner rays", false, CreateDescription());
    OnChanged(configShowSpawnerRays, Tag.SpawnerRay, SpawnArea_Awake.RebuildLoaded);
    configShowSpawnerTriggerRanges = config.Bind(section, "Creature spawner trigger ranges", false, CreateDescription());
    OnChanged(configShowSpawnerTriggerRanges, Tag.SpawnerTriggerRange, SpawnArea_Awake.RebuildLoaded);
    configShowSpawnerLimitRanges = config.Bind(section, "Creature spawner limit ranges", false, CreateDescription());
    OnChanged(configShowSpawnerLimitRanges, Tag.SpawnerLimitRange, SpawnArea_Awake.RebuildLoaded);
    configShowSpawnerSpawnRanges = config.Bind(section, "Creature spawner spawn ranges", false, CreateDescription());
    OnChanged(configShowSpawnerSpawnRanges, Tag.SpawnerSpawnRange, SpawnArea_Awake.RebuildLoaded);
    configShowAltarRays = config.Bind(section, "Altar rays", false, CreateDescription());
    OnChanged(configShowAltarRays, Tag.AltarRay, OfferingBowl_Awake.RebuildLoaded);
    configShowAltarItemStandRange = config.Bind(section, "Altar item stand range", false, CreateDescription());
    OnChanged(configShowAltarItemStandRange, Tag.AltarItemStandRange, OfferingBowl_Awake.RebuildLoaded);
    configShowAltarSpawnRadius = config.Bind(section, "Altar spawn radius", false, CreateDescription());
    OnChanged(configShowAltarSpawnRadius, Tag.AltarSpawnRadius, OfferingBowl_Awake.RebuildLoaded);
    configShowSpawnZones = config.Bind(section, "Spawn zones", false, CreateDescription());
    OnChanged(configShowSpawnZones, Tag.SpawnZoneAshlands, SpawnSystem_Awake.RebuildLoaded);
    OnChanged(configShowSpawnZones, Tag.SpawnZoneBlackForest);
    OnChanged(configShowSpawnZones, Tag.SpawnZoneDeepNorth);
    OnChanged(configShowSpawnZones, Tag.SpawnZoneMeadows);
    OnChanged(configShowSpawnZones, Tag.SpawnZoneMistlands);
    OnChanged(configShowSpawnZones, Tag.SpawnZoneMountain);
    OnChanged(configShowSpawnZones, Tag.SpawnZoneOcean);
    OnChanged(configShowSpawnZones, Tag.SpawnZonePlains);
    OnChanged(configShowSpawnZones, Tag.SpawnZoneSwamp);
    OnChanged(configShowSpawnZones, Tag.SpawnZoneUnknown);
    configShowZoneCorners = config.Bind(section, "Zone corner rays", false, CreateDescription());
    OnChanged(configShowZoneCorners, Tag.ZoneCornerAshlands, SpawnSystem_Awake.RebuildLoaded);
    OnChanged(configShowZoneCorners, Tag.ZoneCornerBlackForest);
    OnChanged(configShowZoneCorners, Tag.ZoneCornerDeepNorth);
    OnChanged(configShowZoneCorners, Tag.ZoneCornerMeadows);
    OnChanged(configShowZoneCorners, Tag.ZoneCornerMistlands);
    OnChanged(configShowZoneCorners, Tag.ZoneCornerMountain);
    OnChanged(configShowZoneCorners, Tag.ZoneCornerOcean);
    OnChanged(configShowZoneCorners, Tag.ZoneCornerPlains);
    OnChanged(configShowZoneCorners, Tag.ZoneCornerSwamp);
    OnChanged(configShowZoneCorners, Tag.ZoneCornerUnknown);
    configShowRandomEventSystem = config.Bind(section, "Random event system", false, CreateDescription());
    OnChanged(configShowRandomEventSystem, Tag.RandomEventSystem, SpawnSystem_Awake.RebuildLoaded);
    configShowEffectAreasBurning = config.Bind(section, "Area effects: Burning", false, CreateDescription());
    OnChanged(configShowEffectAreasBurning, Tag.EffectAreaBurning, EffectArea_Visual.RebuildLoaded);
    configShowEffectAreasComfort = config.Bind(section, "Area effects: Comfort", false, CreateDescription());
    OnChanged(configShowEffectAreasComfort, Tag.EffectAreaComfort, Piece_Visual.RebuildLoaded);
    configShowEffectAreasCustomContainer = config.Bind(section, "Area effects: Custom container", false, CreateDescription());
    OnChanged(configShowEffectAreasCustomContainer, Tag.EffectAreaCustomContainer, Piece_Visual.RebuildLoaded);
    configShowEffectAreasCustomCrafting = config.Bind(section, "Area effects: Custom crafting", false, CreateDescription());
    OnChanged(configShowEffectAreasCustomCrafting, Tag.EffectAreaCustomCrafting, Piece_Visual.RebuildLoaded);
    configShowEffectAreasFire = config.Bind(section, "Area effects: Fire", false, CreateDescription());
    OnChanged(configShowEffectAreasFire, Tag.EffectAreaFire, EffectArea_Visual.RebuildLoaded);
    configShowEffectAreasHeat = config.Bind(section, "Area effects: Heat", false, CreateDescription());
    OnChanged(configShowEffectAreasHeat, Tag.EffectAreaHeat, EffectArea_Visual.RebuildLoaded);
    configShowEffectAreasNoMonsters = config.Bind(section, "Area effects: No monsters", false, CreateDescription());
    OnChanged(configShowEffectAreasNoMonsters, Tag.EffectAreaNoMonsters, EffectArea_Visual.RebuildLoaded);
    configShowEffectAreasOther = config.Bind(section, "Area effects: Other", false, CreateDescription());
    OnChanged(configShowEffectAreasOther, Tag.EffectAreaOther, EffectArea_Visual.RebuildLoaded);
    configShowSpawnSuppression = config.Bind(section, "Area effects: Spawn suppression", false, CreateDescription());
    configShowSpawnSuppression.SettingChanged += (s, e) => BaseRuler.Visible = configShowSpawnSuppression.Value;
    BaseRuler.Visible = configShowSpawnSuppression.Value;

    configShowEffectAreasWarmCozy = config.Bind(section, "Area effects: Warm cozy", false, CreateDescription());
    OnChanged(configShowEffectAreasWarmCozy, Tag.EffectAreaWarmCozy, EffectArea_Visual.RebuildLoaded);
    configShowEffectAreasPrivateArea = config.Bind(section, "Area effects: Private area", false, CreateDescription());
    OnChanged(configShowEffectAreasPrivateArea, Tag.EffectAreaPrivateArea, PrivateArea_Visual.RebuildLoaded);
    configShowEffectAreasTeleport = config.Bind(section, "Area effects: Teleport", false, CreateDescription());
    OnChanged(configShowEffectAreasTeleport, Tag.EffectAreaTeleport, EffectArea_Visual.RebuildLoaded);
    configShowSmoke = config.Bind(section, "Smoke", false, CreateDescription());
    OnChanged(configShowSmoke, Tag.Smoke, Smoke_Visual.RebuildLoaded);
    configShowPlayerCover = config.Bind(section, "Player cover", false, CreateDescription());
    OnChanged(configShowPlayerCover, Tag.PlayerCover, Player_Cover.RebuildLoaded);
    OnChanged(configShowPlayerCover, Tag.PlayerCoverBlocked, Player_Cover.RebuildLoaded);
    Visibility.SetTag(Tag.Terrain, true);
  }
}
